wget -c "https://raw.githubusercontent.com/gioxx/xfiles/master/experimental.txt" -O "lists/experimental.txt"
wget -c "https://raw.githubusercontent.com/gioxx/xfiles/master/facebook.txt" -O "lists/facebook.txt"
wget -c "https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt" -O "lists/filtri.txt"
wget -c "https://raw.githubusercontent.com/gioxx/xfiles/master/fritz/fritz_blacklist.txt" -O "lists/fritz_blacklist.txt"
wget -c "https://raw.githubusercontent.com/gioxx/xfiles/master/siteblock.txt" -O "lists/siteblock.txt"
wget -c "https://raw.githubusercontent.com/gioxx/xfiles/master/upd.txt" -O "lists/upd.txt"
