name: NoAds Lists update
on:
  schedule:
  - cron: '00 10 * * *'
  
  workflow_dispatch:

jobs:
  noads_lists:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Rome"

      - name: Set date and time and downloads lists
        run: |
          sh ./sh/datetime.sh
          sh ./sh/download.sh

      - name: Commit lists
        run: |
          git config --local user.email "114237374+GWall-bot@users.noreply.github.com"
          git config --local user.name "GWall[bot]"
          git add lists/*
          git commit -m "Aggiornamento liste del $checkwebsite" -a
      
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GHUB_TOKEN }}
          branch: ${{ github.ref }}
          
      - name: Copy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./lists/
