name: NoAds Lists update
on:
  schedule:
  - cron: '00 10 * * *'

  workflow_dispatch:

jobs:
  noads_lists:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set Timezone ⌚
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Europe/Rome"

      - name: Update lists ☣️
        run: |
          sh ./sh/datetime.sh
          sh ./sh/download.sh
          git config --local user.email "114237374+GWall-bot@users.noreply.github.com"
          git config --local user.name "GWall[bot]"
          git add lists/*
          git commit -m "Aggiornamento liste del ${{ env.checkwebsite }}" -a

      - name: Push changes 🚀
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Copy to FTP 🔌
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./lists/
